preprocessing:
  random_state: 42
  test_size: 0.2

cluster_select:
  init: 'k-means++'
  max_iter: 100
  random_state: 0
  n_init: 10
  k:  [ 2 , 15]

training_params:
  init: "k-means++"
  n_init: 10
  max_iter: 100
  random_state: 0
  training_path: 'data/processed/train.csv'